### ISSUE TITLE
DApp submit field 'name' returns 404 if no characters

### ISSUE THREAD

**Issue by robyedlin** [state-of-the-dapps/sotd-www#80]
And errors don't fire.

**Comment by robyedlin** [comment]
Make sure any 404 error is handled by axios

**Comment by robyedlin** [comment]
@jorisbontje I think the api should just return an empty object at `/dapps/` (as opposed to `/dapps`). Not sure that building a new method in the client just for that case is worth it. LMK.

**Comment by robyedlin** [comment]
Resolved via https://github.com/state-of-the-dapps/sotd-api/commit/12956804bd70089c0792d2907517993557365266

**Comment by jorisbontje** [comment]
not fixed:

when loading http://localhost:3000/dapps/ it triggers:
```
127.0.0.1 - - [23/Oct/2017 21:13:58] "GET /v1/dapps/undefined HTTP/1.1" 200 -
```

**Comment by robyedlin** [comment]
The rendering is a different issue, which is still in progress:

https://github.com/state-of-the-dapps/sotd-www/issues/67

This resolves the /dapps/ call from the submit page
